setopt nobeep
setopt interactive_comments
setopt correct
setopt chase_links
setopt chase_dots

# history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt append_history
setopt share_history
setopt extended_history
setopt histignoredups
setopt histignorealldups
setopt histignorespace
setopt hist_reduce_blanks
setopt inc_append_history
setopt hist_verify

# completion
autoload -U compinit
compinit
setopt auto_menu
unsetopt menu_complete
setopt completealiases
zstyle ':completion::complete:*' use-cache 1
zstyle ":completion:*" menu select
zstyle ":completion:*" rehash true # complete new commands
zstyle ':completion:*' group-name '' # group results
zstyle ':completion:*' squeeze-slashes true # expand // to /
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ":completion:*:processes" command "ps -au$USER"
zstyle ":completion:*:processes-names" command "ps c -u ${USER} -o command | uniq"

# fix keys in st
bindkey "^[[P" delete-char
bindkey  "^[[H" beginning-of-line
bindkey "^[[4~"  end-of-line

# bash-like search
bindkey '^R' history-incremental-pattern-search-backward

# up / down arrow search
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# exists helper
_exists() { type $1 > /dev/null }

# convenience
alias mkdir="mkdir -p"
alias df="df -h"
alias du="du -h"
alias ..='cd ..'
alias ...='cd ../..'
_exists vim && alias vi="vim"
_exists doas && alias sudo="doas"
alias stopwatch="time cat"

# global aliases
alias -g ~c="| wc -l"
alias -g ~n="> /dev/null 2>&1"
alias -g ~s="| curl -F 'sprunge=<-' http://sprunge.us"

# env vars
export MANWIDTH=80
export LESSHISTFILE=-
_exists vim && export EDITOR="vim"
_exists less && export PAGER="less"
_exists brave-bin && export BROWSER="brave-bin"
_exists brave-browser && export BROWSER="brave-browser"
_exists systemctl && export SYSTEMD_PAGER=

# deeply nested folders
function up {
	if [[ "$#" < 1 ]] ; then
		cd ..
	else
		CDSTR=""
		for i in {1..$1} ; do
			CDSTR="../$CDSTR"
		done
		cd $CDSTR
	fi
}

# starship prompt
_exists starship && eval "$(starship init zsh)"

# undefine exists helper
unfunction _exists
